### ISSUE TITLE
使用JarCilent报错：org.json.JSONArray 无法映射到 java.lang.String

### ISSUE THREAD

**Issue by CyberKanjousen** [BalloonUpdate/JarClient#15]
用PS启动JarClient的日志如下：
```
PS D:\dwb\(整合包名)\.minecraft\versions\(整合包名)> java -jar JarClient.jar #不包含中文路径
GraphicsMode:         true
Standalone:           true
updating directory:   D:/dwb/(整合包名)/.minecraft/versions/(整合包名)/.
working directory:    D:/dwb/(整合包名)/.minecraft/versions/(整合包名)
executable directory: D:/dwb/(整合包名)/.minecraft/versions/(整合包名)
application version:  4.1.18 (a20a06a449f8a0cf398ec127ade78c63af5cbc55)
java virtual machine: Oracle Corporation 1.8.0_333
operating system: Windows 11 10.0 amd64
http request on http://mcpack.dwbrss.xyz/index.php
java.lang.ClassCastException #这以下应该就是报错部分了
java.lang.ClassCastException: java.lang.String cannot be cast to org.json.JSONArray
        at com.github.balloonupdate.WorkThread.requestIndex(WorkThread.kt:352)
        at com.github.balloonupdate.WorkThread.run(WorkThread.kt:41)

Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to org.json.JSONArray
        at com.github.balloonupdate.WorkThread.requestIndex(WorkThread.kt:352)
        at com.github.balloonupdate.WorkThread.run(WorkThread.kt:41)
```

**Comment by asforest** [comment]
非常抱歉现在才看到这个Issue，不知道为啥我没有收到GitHub的通知邮件。
关于这个问题，你先试试访问一下出错的这个URL，用浏览器，比较大的可能性是备案阻断页面，或者樱花映射的阻断页面导致数据解析失败
